### PR TITLE
Fix #331 and #403 (properly this time)

### LINKED ISSUE #331: Bot assassination bug
**Describe the bug**
Bots don't assassinate 🙃 

**To Reproduce**
1. Create game where bot is assassin
2. Succeed 3 missions as res

**Expected behavior**
Bot randomly picks a target to kill

**Screenshots**
[
Screen Shot 2020-05-03 at 2 31 31 AM
](url)

### PR DESCRIPTION
**Pull request by sleepyfoxen**
- #403 is fixed sort of hackily by asserting the hammer has not been rejected before processing bot moves
- #331 triggers in games with lovers, where there are options for the number of players the bot can shoot. Checks in the code expected a number, where the type could be a number or an array, or null/undefined.

### CODE REVIEW

File: src/gameplay/game.ts [hunk 1]
```diff
@@ -594,6 +594,10 @@ Game.prototype.checkBotMoves = function (pendingBots) {
 
   // Players whose moves we're waiting for
   this.interval = setInterval(() => {
+    // hack: check for hammer reject
+    if (thisRoom.howWasWon === 'Hammer rejected.')
+      thisRoom.finished = true;
```
Comment (vck3000) [inline src/gameplay/game.ts:599]: Could I ask you to curly bracket this part please? We had a pretty bad issue in the past caused by the lack of curly brackets. Could you also fix up the one in bot.js too?
